apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: rhel-server
    app.kubernetes.io/component: rhel-server
    app.kubernetes.io/instance: rhel-server
  name: rhel-server
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: rhel-server
  type: ClusterIP
