apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - args:
    - bash
    - -c
    - mkdir -p /tmp/test; cd /tmp/test; echo "WELCOME!" > index.html; nohup
      sleep 10 & python -m SimpleHTTPServer 8080
    image: registry.redhat.io/rhel7
    imagePullPolicy: Always
    name: test-app
    ports:
    - containerPort: 8080
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
